# Generated by Django 4.1.3 on 2023-02-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_name", models.TextField(max_length=100)),
                ("cust_contact", models.TextField(max_length=10)),
                ("cust_address", models.TextField(max_length=100)),
                ("cust_dob", models.DateField()),
                ("cust_username", models.TextField(max_length=100)),
                ("cust_password", models.TextField(max_length=100)),
            ],
        ),
    ]
