# Generated by Django 4.1.3 on 2023-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="cust_gender",
            field=models.TextField(max_length=10, null=True),
        ),
    ]
